[package]
name = "mqtt"
version = "0.1.0"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
itertools = "0.8"
log = "0.4"
tokio = "0.1"

[dev-dependencies]
structopt = "0.2"
structopt-derive = "0.2"
env_logger = "0.6"
